name: Author to CODEOWNERS
description: 'Last authors written to CODEOWNERS'
author: 'Dmitriy Krasnikov'
branding:
  icon: '??'
  color: 'red'
inputs:
  token:
    description: 'GitHub token for GitHub API requests.'
    required: true
    default: ${{ github.token }}
  directory_to_track:
    description: 'The directory to monitor'
    required: true
  number_of_code_owners:
    description: 'The number of historical codeowners to keep per source file'
    required: false
    default: 2
outputs:
  file:
    description: 'The CODEOWNERS file'
runs:
  using: 'node12'
  main: 'dist/index.js'
