name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: create CODEOWNERS
        id: codeowners
        uses: dmikov/github-action-codeowners-last@main
        with:
          number_of_code_owners: 2
      - name: commit CODEOWNERS
        id: committed
        if: ${{ steps.committed.outputs.changes_detected == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: 'chore(meta): update code owners'
          file_pattern: ${{ steps.codeowners.file }}