name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: dmikov/github-action-codeowners-last@main
        with:
          directory_to_track: /
          number_of_code_owners: 2