name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: create CODEOWNERS
        id: codeowners
        uses: dmikov/github-action-codeowners-last@main
        with:
          number_of_code_owners: 2
      - name: commit CODEOWNERS
        if: ${{ steps.codeowners.outputs.file }}
        uses: EndBug/add-and-commit@v5
        with:
          message: 'commit CODEOWNERS'
          add: ${{ steps.codeowners.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}